GET http://localhost:3000/songs

### show song
GET http://localhost:3000/songs/3

### Index songwriters
GET http://localhost:3000/songwriters

### Index shows
GET http://localhost:3000/shows

### Index genres
GET http://localhost:3000/genres

### Index tempos
GET http://localhost:3000/tempos

### User sign up
POST http://localhost:3000/users
content-type: application/json

{
  "name": "Frodo Baggins",
  "email": "frodo@email.com",
  "password": "password",
  "password_confirmation": "password"
}

### User log in
POST http://localhost:3000/sessions
content-type: application/json

{
  "email": "sam@email.com",
  "password": "password"
}

### create saved song
POST http://localhost:3000/saved_songs
Content-Type: application/json

{
  "song_id": 3,
  "user_id": 1
}

### index saved songs
GET http://localhost:3000/saved_songs
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTIzOTU3MDJ9.RA7GEgYvpU9p3x1xBP6Jv7EmZHeRVPdEtL2LyN2GBlQ

### index notes
GET http://localhost:3000/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTIzOTU3MDJ9.RA7GEgYvpU9p3x1xBP6Jv7EmZHeRVPdEtL2LyN2GBlQ

### create note
POST http://localhost:3000/notes
Authorization: Bearer 
Content-Type: application/json

{
  "description": "testing this note",
  "saved_song_id": 2
  }

### update notes
PATCH http://localhost:3000/notes/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTIzOTU3MDJ9.RA7GEgYvpU9p3x1xBP6Jv7EmZHeRVPdEtL2LyN2GBlQ
Content-Type: application/json

{
  "description": "changing my test note!!!!!!"
}

### update notes
DELETE http://localhost:3000/notes/3