GET http://localhost:3000/songs


### show song
GET http://localhost:3000/songs/3

### Index songwriters
GET http://localhost:3000/songwriters

### Index shows
GET http://localhost:3000/shows

### Index genres
GET http://localhost:3000/genres
