GET http://localhost:3000/songs?composer=Lisa+Kron&title=Into+the+Woods

### show song
GET http://localhost:3000/songs/3

### Index songwriters
GET http://localhost:3000/songwriters

### Index shows
GET http://localhost:3000/shows
